### ISSUE TITLE
Todo. change default branch

### ISSUE THREAD

**Issue by diligejy** [dl4ab/attend-bot#3]
출석체크 봇 github default branch를 source branch로 전환시킨 후 이 branch를 거쳐 master branch로 merge하도록 설정

**Comment by kkweon** [comment]
왜 필요하죠?

**Comment by diligejy** [comment]
Todo를 슬랙이 아닌 github에 적어놓으려구요.

**Comment by kkweon** [comment]
이전부터 대화가 제대로 안된다고 느끼는군요. 제가 아무래도 가정을 너무 많이 한 것 같습니다.

출석체크 봇 github default branch를 source branch로 전환시킨 후 이 branch를 거쳐 master branch로 merge하도록 설정하는게 왜 필요하죠?

master  브랜치 그대로 사용하면 될 것 같습니다. 마스터 브랜치는 PR 로 업데이트하구요.

**Comment by diligejy** [comment]
아 이제 이해했습니다.

넵 그렇게 하겠습니다.
